[package]
name = "lexer"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"] }

[build-dependencies]
csv = "1.1"
Inflector = "0.11"
serde = { version = "1.0", features = ["derive"] }
