use super::{Code, funcs::EncoderTrait, InstructionData, OperandType};

macro_rules! id {
    ($operation:ident, $op_code:literal, $destination:ident, $source:ident, $encoder:ident, $codes:expr) => {{
        InstructionData {
            operation: Operation::$operation,
            op_code: $op_code,
            destination: OperandType::$destination,
            source: OperandType::$source,
            encoder: super::funcs::$encoder::encode,
            sizer: super::funcs::$encoder::size,
            codes: $codes,
        }
    }};
}

#[rustfmt::skip]
pub const DATA: &[InstructionData] = &[
    id!(Aaa, 0x00, none, none, bytes_only, &[Code::byte(0x37)]),
    id!(Aad, 0x00, none, none, bytes_only, &[Code::byte(0xd5), Code::byte(0x0a)]),
    id!(Aad, 0x00, imm, none, immediate, &[Code::byte(0xd5), Code::ib]),
    id!(Aam, 0x00, none, none, bytes_only, &[Code::byte(0xd4), Code::byte(0x0a)]),
    id!(Aam, 0x00, imm, none, immediate, &[Code::byte(0xd4), Code::ib]),
    id!(Aas, 0x00, none, none, bytes_only, &[Code::byte(0x3f)]),
    id!(Adc, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x10), Code::mrm]),
    id!(Adc, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x10), Code::mrm]),
    id!(Adc, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x11), Code::mrm]),
    id!(Adc, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x11), Code::mrm]),
    id!(Adc, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x12), Code::mrm]),
    id!(Adc, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x12), Code::mrm]),
    id!(Adc, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x13), Code::mrm]),
    id!(Adc, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x13), Code::mrm]),
    id!(Adc, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x02), Code::ibs]),
    id!(Adc, 0x00, al, imm, immediate_source, &[Code::byte(0x14), Code::ib]),
    id!(Adc, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x02), Code::ibs]),
    id!(Adc, 0x00, ax, imm, immediate_source, &[Code::byte(0x15), Code::iw]),
    id!(Adc, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x02), Code::ib]),
    id!(Adc, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x02), Code::ibs]),
    id!(Adc, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x02), Code::iw]),
    id!(Adc, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x02), Code::ib]),
    id!(Adc, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x02), Code::ibs]),
    id!(Adc, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x02), Code::iw]),
    id!(Adc, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x02), Code::ib]),
    id!(Add, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x00), Code::mrm]),
    id!(Add, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x00), Code::mrm]),
    id!(Add, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x01), Code::mrm]),
    id!(Add, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x01), Code::mrm]),
    id!(Add, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x02), Code::mrm]),
    id!(Add, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x02), Code::mrm]),
    id!(Add, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x03), Code::mrm]),
    id!(Add, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x03), Code::mrm]),
    id!(Add, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x00), Code::ibs]),
    id!(Add, 0x00, al, imm, immediate_source, &[Code::byte(0x04), Code::ib]),
    id!(Add, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x00), Code::ibs]),
    id!(Add, 0x00, ax, imm, immediate_source, &[Code::byte(0x05), Code::iw]),
    id!(Add, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x00), Code::ib]),
    id!(Add, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x00), Code::ibs]),
    id!(Add, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x00), Code::iw]),
    id!(Add, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x00), Code::ib]),
    id!(Add, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x00), Code::ibs]),
    id!(Add, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x00), Code::iw]),
    id!(Add, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x00), Code::ib]),
    id!(And, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x20), Code::mrm]),
    id!(And, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x20), Code::mrm]),
    id!(And, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x21), Code::mrm]),
    id!(And, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x21), Code::mrm]),
    id!(And, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x22), Code::mrm]),
    id!(And, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x22), Code::mrm]),
    id!(And, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x23), Code::mrm]),
    id!(And, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x23), Code::mrm]),
    id!(And, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x04), Code::ibs]),
    id!(And, 0x00, al, imm, immediate_source, &[Code::byte(0x24), Code::ib]),
    id!(And, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x04), Code::ibs]),
    id!(And, 0x00, ax, imm, immediate_source, &[Code::byte(0x25), Code::iw]),
    id!(And, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x04), Code::ib]),
    id!(And, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x04), Code::ibs]),
    id!(And, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x04), Code::iw]),
    id!(And, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x04), Code::ib]),
    id!(And, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x04), Code::ibs]),
    id!(And, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x04), Code::iw]),
    id!(And, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x04), Code::ib]),
    id!(Call, 0x00, imm, none, immediate, &[Code::byte(0xe8), Code::rel]),
    id!(Call, 0x00, imm, none, immediate, &[Code::byte(0xe8), Code::rel]),
    id!(Call, 0x00, imm, none, immediate, &[Code::byte(0x9a), Code::iwd, Code::seg]),
    id!(Call, 0x00, imm16, none, immediate, &[Code::byte(0xe8), Code::rel]),
    id!(Call, 0x00, imm16, none, immediate, &[Code::byte(0xe8), Code::rel]),
    id!(Call, 0x00, imm16, none, immediate, &[Code::byte(0x9a), Code::iwd, Code::seg]),
    id!(Call, 0x00, seg_off, none, jump_immediate, &[Code::byte(0x9a), Code::iwd, Code::iw]),
    id!(Call, 0x00, seg_off, none, jump_immediate, &[Code::byte(0x9a), Code::iw, Code::iw]),
    id!(Call, 0x00, seg_off, none, jump_immediate, &[Code::byte(0x9a), Code::iw, Code::iw]),
    id!(Call, 0x00, mem, none, memory, &[Code::byte(0xff), Code::encoding(0x03)]),
    id!(Call, 0x00, mem16, none, memory, &[Code::byte(0xff), Code::encoding(0x03)]),
    id!(Call, 0x00, mem, none, memory, &[Code::byte(0xff), Code::encoding(0x02)]),
    id!(Call, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x02)]),
    id!(Call, 0x00, mem, none, memory, &[Code::byte(0xff), Code::encoding(0x02)]),
    id!(Call, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x02)]),
    id!(Cbw, 0x00, none, none, bytes_only, &[Code::byte(0x98)]),
    id!(Clc, 0x00, none, none, bytes_only, &[Code::byte(0xf8)]),
    id!(Cld, 0x00, none, none, bytes_only, &[Code::byte(0xfc)]),
    id!(Cli, 0x00, none, none, bytes_only, &[Code::byte(0xfa)]),
    id!(Cmc, 0x00, none, none, bytes_only, &[Code::byte(0xf5)]),
    id!(Cmp, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x38), Code::mrm]),
    id!(Cmp, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x38), Code::mrm]),
    id!(Cmp, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x39), Code::mrm]),
    id!(Cmp, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x39), Code::mrm]),
    id!(Cmp, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x3a), Code::mrm]),
    id!(Cmp, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x3a), Code::mrm]),
    id!(Cmp, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x3b), Code::mrm]),
    id!(Cmp, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x3b), Code::mrm]),
    id!(Cmp, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x07), Code::ibs]),
    id!(Cmp, 0x00, al, imm, immediate_source, &[Code::byte(0x3c), Code::ib]),
    id!(Cmp, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x07), Code::ibs]),
    id!(Cmp, 0x00, ax, imm, immediate_source, &[Code::byte(0x3d), Code::iw]),
    id!(Cmp, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x07), Code::ib]),
    id!(Cmp, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x07), Code::ibs]),
    id!(Cmp, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x07), Code::iw]),
    id!(Cmp, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x07), Code::ib]),
    id!(Cmp, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x07), Code::ibs]),
    id!(Cmp, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x07), Code::iw]),
    id!(Cmp, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x07), Code::ib]),
    id!(Cmpsb, 0x00, none, none, bytes_only, &[Code::repe, Code::byte(0xa6)]),
    id!(Cmpsw, 0x00, none, none, bytes_only, &[Code::repe, Code::byte(0xa7)]),
    id!(Cwd, 0x00, none, none, bytes_only, &[Code::byte(0x99)]),
    id!(Daa, 0x00, none, none, bytes_only, &[Code::byte(0x27)]),
    id!(Das, 0x00, none, none, bytes_only, &[Code::byte(0x2f)]),
    id!(Dec, 0x00, reg16, none, register, &[Code::plus_reg(0x48)]),
    id!(Dec, 0x00, rm8, none, memory, &[Code::byte(0xfe), Code::encoding(0x01)]),
    id!(Dec, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x01)]),
    id!(Div, 0x00, rm8, none, memory, &[Code::byte(0xf6), Code::encoding(0x06)]),
    id!(Div, 0x00, rm16, none, memory, &[Code::byte(0xf7), Code::encoding(0x06)]),
    id!(Hlt, 0x00, none, none, bytes_only, &[Code::byte(0xf4)]),
    id!(Idiv, 0x00, rm8, none, memory, &[Code::byte(0xf6), Code::encoding(0x07)]),
    id!(Idiv, 0x00, rm16, none, memory, &[Code::byte(0xf7), Code::encoding(0x07)]),
    id!(Imul, 0x00, rm8, none, memory, &[Code::byte(0xf6), Code::encoding(0x05)]),
    id!(Imul, 0x00, rm16, none, memory, &[Code::byte(0xf7), Code::encoding(0x05)]),
    id!(In, 0x00, al, imm, immediate_source, &[Code::byte(0xe4), Code::ib]),
    id!(In, 0x00, ax, imm, immediate_source, &[Code::byte(0xe5), Code::ib]),
    id!(In, 0x00, al, dx, bytes_only, &[Code::byte(0xec)]),
    id!(In, 0x00, ax, dx, bytes_only, &[Code::byte(0xed)]),
    id!(Inc, 0x00, reg16, none, register, &[Code::plus_reg(0x40)]),
    id!(Inc, 0x00, rm8, none, memory, &[Code::byte(0xfe), Code::encoding(0x00)]),
    id!(Inc, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x00)]),
    id!(Int, 0x00, imm, none, immediate, &[Code::byte(0xcd), Code::ib]),
    id!(Int03, 0x00, none, none, bytes_only, &[Code::byte(0xcc)]),
    id!(Int3, 0x00, none, none, bytes_only, &[Code::byte(0xcc)]),
    id!(Into, 0x00, none, none, bytes_only, &[Code::byte(0xce)]),
    id!(Iret, 0x00, none, none, bytes_only, &[Code::byte(0xcf)]),
    id!(Jcxz, 0x00, imm, none, immediate, &[Code::byte(0xe3), Code::rel8]),
    id!(Jmp, 0x00, imm, none, immediate, &[Code::byte(0xeb), Code::rel8]),
    id!(Jmp, 0x00, imm, none, immediate, &[Code::jmp8, Code::byte(0xeb), Code::rel8]),
    id!(Jmp, 0x00, imm, none, immediate, &[Code::byte(0xe9), Code::rel]),
    id!(Jmp, 0x00, imm, none, immediate, &[Code::byte(0xe9), Code::rel]),
    id!(Jmp, 0x00, imm, none, immediate, &[Code::byte(0xea), Code::iwd, Code::seg]),
    id!(Jmp, 0x00, imm16, none, immediate, &[Code::byte(0xe9), Code::rel]),
    id!(Jmp, 0x00, imm16, none, immediate, &[Code::byte(0xe9), Code::rel]),
    id!(Jmp, 0x00, imm16, none, immediate, &[Code::byte(0xea), Code::iwd, Code::seg]),
    id!(Jmp, 0x00, seg_off, none, jump_immediate, &[Code::byte(0xea), Code::iwd, Code::iw]),
    id!(Jmp, 0x00, seg_off, none, jump_immediate, &[Code::byte(0xea), Code::iw, Code::iw]),
    id!(Jmp, 0x00, seg_off, none, jump_immediate, &[Code::byte(0xea), Code::iw, Code::iw]),
    id!(Jmp, 0x00, mem, none, memory, &[Code::byte(0xff), Code::encoding(0x05)]),
    id!(Jmp, 0x00, mem16, none, memory, &[Code::byte(0xff), Code::encoding(0x05)]),
    id!(Jmp, 0x00, mem, none, memory, &[Code::byte(0xff), Code::encoding(0x04)]),
    id!(Jmp, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x04)]),
    id!(Jmp, 0x00, mem, none, memory, &[Code::byte(0xff), Code::encoding(0x04)]),
    id!(Jmp, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x04)]),
    id!(Lahf, 0x00, none, none, bytes_only, &[Code::byte(0x9f)]),
    id!(Lds, 0x00, reg16, mem, register_and_memory, &[Code::byte(0xc5), Code::mrm]),
    id!(Lea, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x8d), Code::mrm]),
    id!(Lea, 0x00, reg16, imm, register_and_memory, &[Code::byte(0x8d), Code::mrm]),
    id!(Les, 0x00, reg16, mem, register_and_memory, &[Code::byte(0xc4), Code::mrm]),
    id!(Lodsb, 0x00, none, none, bytes_only, &[Code::byte(0xac)]),
    id!(Lodsw, 0x00, none, none, bytes_only, &[Code::byte(0xad)]),
    id!(Loop, 0x00, imm, cx, immediate, &[Code::byte(0xe2), Code::rel8]),
    id!(Loope, 0x00, imm, cx, immediate, &[Code::byte(0xe1), Code::rel8]),
    id!(Loopne, 0x00, imm, cx, immediate, &[Code::byte(0xe0), Code::rel8]),
    id!(Loopnz, 0x00, imm, cx, immediate, &[Code::byte(0xe0), Code::rel8]),
    id!(Loopz, 0x00, imm, cx, immediate, &[Code::byte(0xe1), Code::rel8]),
    id!(Mov, 0x00, mem, seg, memory_and_register, &[Code::byte(0x8c), Code::mrm]),
    id!(Mov, 0x00, reg16, seg, memory_and_register, &[Code::byte(0x8c), Code::mrm]),
    id!(Mov, 0x00, seg, mem, register_and_memory, &[Code::byte(0x8e), Code::mrm]),
    id!(Mov, 0x00, seg, reg16, register_and_memory, &[Code::byte(0x8e), Code::mrm]),
    id!(Mov, 0x00, seg, reg16, register_and_memory, &[Code::byte(0x8e), Code::mrm]),
    id!(Mov, 0x00, al, mem, immediate_source, &[Code::byte(0xa0), Code::iw]),
    id!(Mov, 0x00, ax, mem, immediate_source, &[Code::byte(0xa1), Code::iw]),
    id!(Mov, 0x00, mem, al, immediate, &[Code::byte(0xa2), Code::iw]),
    id!(Mov, 0x00, mem, ax, immediate, &[Code::byte(0xa3), Code::iw]),
    id!(Mov, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x88), Code::mrm]),
    id!(Mov, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x88), Code::mrm]),
    id!(Mov, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x89), Code::mrm]),
    id!(Mov, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x89), Code::mrm]),
    id!(Mov, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x8a), Code::mrm]),
    id!(Mov, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x8a), Code::mrm]),
    id!(Mov, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x8b), Code::mrm]),
    id!(Mov, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x8b), Code::mrm]),
    id!(Mov, 0x00, reg8, imm, register_immediate, &[Code::plus_reg(0xb0), Code::ib]),
    id!(Mov, 0x00, reg16, imm, register_immediate, &[Code::plus_reg(0xb8), Code::iw]),
    id!(Mov, 0x00, rm8, imm, memory_immediate, &[Code::byte(0xc6), Code::encoding(0x00), Code::ib]),
    id!(Mov, 0x00, rm16, imm, memory_immediate, &[Code::byte(0xc7), Code::encoding(0x00), Code::iw]),
    id!(Mov, 0x00, mem, imm8, memory_immediate, &[Code::byte(0xc6), Code::encoding(0x00), Code::ib]),
    id!(Mov, 0x00, mem, imm16, memory_immediate, &[Code::byte(0xc7), Code::encoding(0x00), Code::iw]),
    id!(Movsb, 0x00, none, none, bytes_only, &[Code::byte(0xa4)]),
    id!(Movsw, 0x00, none, none, bytes_only, &[Code::byte(0xa5)]),
    id!(Mul, 0x00, rm8, none, memory, &[Code::byte(0xf6), Code::encoding(0x04)]),
    id!(Mul, 0x00, rm16, none, memory, &[Code::byte(0xf7), Code::encoding(0x04)]),
    id!(Neg, 0x00, rm8, none, memory, &[Code::byte(0xf6), Code::encoding(0x03)]),
    id!(Neg, 0x00, rm16, none, memory, &[Code::byte(0xf7), Code::encoding(0x03)]),
    id!(Nop, 0x00, none, none, bytes_only, &[Code::byte(0x90)]),
    id!(Not, 0x00, rm8, none, memory, &[Code::byte(0xf6), Code::encoding(0x02)]),
    id!(Not, 0x00, rm16, none, memory, &[Code::byte(0xf7), Code::encoding(0x02)]),
    id!(Or, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x08), Code::mrm]),
    id!(Or, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x08), Code::mrm]),
    id!(Or, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x09), Code::mrm]),
    id!(Or, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x09), Code::mrm]),
    id!(Or, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x0a), Code::mrm]),
    id!(Or, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x0a), Code::mrm]),
    id!(Or, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x0b), Code::mrm]),
    id!(Or, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x0b), Code::mrm]),
    id!(Or, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x01), Code::ibs]),
    id!(Or, 0x00, al, imm, immediate_source, &[Code::byte(0x0c), Code::ib]),
    id!(Or, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x01), Code::ibs]),
    id!(Or, 0x00, ax, imm, immediate_source, &[Code::byte(0x0d), Code::iw]),
    id!(Or, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x01), Code::ib]),
    id!(Or, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x01), Code::ibs]),
    id!(Or, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x01), Code::iw]),
    id!(Or, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x01), Code::ib]),
    id!(Or, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x01), Code::ibs]),
    id!(Or, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x01), Code::iw]),
    id!(Or, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x01), Code::ib]),
    id!(Out, 0x00, imm, al, immediate, &[Code::byte(0xe6), Code::ib]),
    id!(Out, 0x00, imm, ax, immediate, &[Code::byte(0xe7), Code::ib]),
    id!(Out, 0x00, dx, al, bytes_only, &[Code::byte(0xee)]),
    id!(Out, 0x00, dx, ax, bytes_only, &[Code::byte(0xef)]),
    id!(Pop, 0x00, reg16, none, register, &[Code::plus_reg(0x58)]),
    id!(Pop, 0x00, rm16, none, memory, &[Code::byte(0x8f), Code::encoding(0x00)]),
    id!(Pop, 0x00, es, none, bytes_only, &[Code::byte(0x07)]),
    id!(Pop, 0x00, cs, none, bytes_only, &[Code::byte(0x0f)]),
    id!(Pop, 0x00, ss, none, bytes_only, &[Code::byte(0x17)]),
    id!(Pop, 0x00, ds, none, bytes_only, &[Code::byte(0x1f)]),
    id!(Popf, 0x00, none, none, bytes_only, &[Code::byte(0x9d)]),
    id!(Popfw, 0x00, none, none, bytes_only, &[Code::byte(0x9d)]),
    id!(Push, 0x00, reg16, none, register, &[Code::plus_reg(0x50)]),
    id!(Push, 0x00, rm16, none, memory, &[Code::byte(0xff), Code::encoding(0x06)]),
    id!(Push, 0x00, es, none, bytes_only, &[Code::byte(0x06)]),
    id!(Push, 0x00, cs, none, bytes_only, &[Code::byte(0x0e)]),
    id!(Push, 0x00, ss, none, bytes_only, &[Code::byte(0x16)]),
    id!(Push, 0x00, ds, none, bytes_only, &[Code::byte(0x1e)]),
    id!(Pushf, 0x00, none, none, bytes_only, &[Code::byte(0x9c)]),
    id!(Pushfw, 0x00, none, none, bytes_only, &[Code::byte(0x9c)]),
    id!(Rcl, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x02)]),
    id!(Rcl, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x02)]),
    id!(Rcl, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x02)]),
    id!(Rcl, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x02)]),
    id!(Rcr, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x03)]),
    id!(Rcr, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x03)]),
    id!(Rcr, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x03)]),
    id!(Rcr, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x03)]),
    id!(Ret, 0x00, none, none, bytes_only, &[Code::byte(0xc3)]),
    id!(Ret, 0x00, imm, none, immediate, &[Code::byte(0xc2), Code::iw]),
    id!(Retf, 0x00, none, none, bytes_only, &[Code::byte(0xcb)]),
    id!(Retf, 0x00, imm, none, immediate, &[Code::byte(0xca), Code::iw]),
    id!(Rol, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x00)]),
    id!(Rol, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x00)]),
    id!(Rol, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x00)]),
    id!(Rol, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x00)]),
    id!(Ror, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x01)]),
    id!(Ror, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x01)]),
    id!(Ror, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x01)]),
    id!(Ror, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x01)]),
    id!(Sahf, 0x00, none, none, bytes_only, &[Code::byte(0x9e)]),
    id!(Sal, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x04)]),
    id!(Sal, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x04)]),
    id!(Sal, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x04)]),
    id!(Sal, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x04)]),
    id!(Salc, 0x00, none, none, bytes_only, &[Code::byte(0xd6)]),
    id!(Sar, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x07)]),
    id!(Sar, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x07)]),
    id!(Sar, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x07)]),
    id!(Sar, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x07)]),
    id!(Sbb, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x18), Code::mrm]),
    id!(Sbb, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x18), Code::mrm]),
    id!(Sbb, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x19), Code::mrm]),
    id!(Sbb, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x19), Code::mrm]),
    id!(Sbb, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x1a), Code::mrm]),
    id!(Sbb, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x1a), Code::mrm]),
    id!(Sbb, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x1b), Code::mrm]),
    id!(Sbb, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x1b), Code::mrm]),
    id!(Sbb, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x03), Code::ibs]),
    id!(Sbb, 0x00, al, imm, immediate_source, &[Code::byte(0x1c), Code::ib]),
    id!(Sbb, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x03), Code::ibs]),
    id!(Sbb, 0x00, ax, imm, immediate_source, &[Code::byte(0x1d), Code::iw]),
    id!(Sbb, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x03), Code::ib]),
    id!(Sbb, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x03), Code::ibs]),
    id!(Sbb, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x03), Code::iw]),
    id!(Sbb, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x03), Code::ib]),
    id!(Sbb, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x03), Code::ibs]),
    id!(Sbb, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x03), Code::iw]),
    id!(Sbb, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x03), Code::ib]),
    id!(Scasb, 0x00, none, none, bytes_only, &[Code::repe, Code::byte(0xae)]),
    id!(Scasw, 0x00, none, none, bytes_only, &[Code::repe, Code::byte(0xaf)]),
    id!(Shl, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x04)]),
    id!(Shl, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x04)]),
    id!(Shl, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x04)]),
    id!(Shl, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x04)]),
    id!(Shr, 0x00, rm8, one, memory, &[Code::byte(0xd0), Code::encoding(0x05)]),
    id!(Shr, 0x00, rm8, cl, memory, &[Code::byte(0xd2), Code::encoding(0x05)]),
    id!(Shr, 0x00, rm16, one, memory, &[Code::byte(0xd1), Code::encoding(0x05)]),
    id!(Shr, 0x00, rm16, cl, memory, &[Code::byte(0xd3), Code::encoding(0x05)]),
    id!(Stc, 0x00, none, none, bytes_only, &[Code::byte(0xf9)]),
    id!(Std, 0x00, none, none, bytes_only, &[Code::byte(0xfd)]),
    id!(Sti, 0x00, none, none, bytes_only, &[Code::byte(0xfb)]),
    id!(Stosb, 0x00, none, none, bytes_only, &[Code::byte(0xaa)]),
    id!(Stosw, 0x00, none, none, bytes_only, &[Code::byte(0xab)]),
    id!(Sub, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x28), Code::mrm]),
    id!(Sub, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x28), Code::mrm]),
    id!(Sub, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x29), Code::mrm]),
    id!(Sub, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x29), Code::mrm]),
    id!(Sub, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x2a), Code::mrm]),
    id!(Sub, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x2a), Code::mrm]),
    id!(Sub, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x2b), Code::mrm]),
    id!(Sub, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x2b), Code::mrm]),
    id!(Sub, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x05), Code::ibs]),
    id!(Sub, 0x00, al, imm, immediate_source, &[Code::byte(0x2c), Code::ib]),
    id!(Sub, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x05), Code::ibs]),
    id!(Sub, 0x00, ax, imm, immediate_source, &[Code::byte(0x2d), Code::iw]),
    id!(Sub, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x05), Code::ib]),
    id!(Sub, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x05), Code::ibs]),
    id!(Sub, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x05), Code::iw]),
    id!(Sub, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x05), Code::ib]),
    id!(Sub, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x05), Code::ibs]),
    id!(Sub, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x05), Code::iw]),
    id!(Sub, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x05), Code::ib]),
    id!(Test, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x84), Code::mrm]),
    id!(Test, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x84), Code::mrm]),
    id!(Test, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x85), Code::mrm]),
    id!(Test, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x85), Code::mrm]),
    id!(Test, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x84), Code::mrm]),
    id!(Test, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x85), Code::mrm]),
    id!(Test, 0x00, al, imm, immediate_source, &[Code::byte(0xa8), Code::ib]),
    id!(Test, 0x00, ax, imm, immediate_source, &[Code::byte(0xa9), Code::iw]),
    id!(Test, 0x00, rm8, imm, memory_immediate, &[Code::byte(0xf6), Code::encoding(0x00), Code::ib]),
    id!(Test, 0x00, rm16, imm, memory_immediate, &[Code::byte(0xf7), Code::encoding(0x00), Code::iw]),
    id!(Test, 0x00, mem, imm8, memory_immediate, &[Code::byte(0xf6), Code::encoding(0x00), Code::ib]),
    id!(Test, 0x00, mem, imm16, memory_immediate, &[Code::byte(0xf7), Code::encoding(0x00), Code::iw]),
    id!(Fwait, 0x00, none, none, bytes_only, &[Code::wait]),
    id!(Xchg, 0x00, ax, reg16, register_source, &[Code::plus_reg(0x90)]),
    id!(Xchg, 0x00, reg16, ax, register, &[Code::plus_reg(0x90)]),
    id!(Xchg, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x86), Code::mrm]),
    id!(Xchg, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x86), Code::mrm]),
    id!(Xchg, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x87), Code::mrm]),
    id!(Xchg, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x87), Code::mrm]),
    id!(Xchg, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x86), Code::mrm]),
    id!(Xchg, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x86), Code::mrm]),
    id!(Xchg, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x87), Code::mrm]),
    id!(Xchg, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x87), Code::mrm]),
    id!(Xlatb, 0x00, none, none, bytes_only, &[Code::byte(0xd7)]),
    id!(Xlat, 0x00, none, none, bytes_only, &[Code::byte(0xd7)]),
    id!(Xor, 0x00, mem, reg8, memory_and_register, &[Code::byte(0x30), Code::mrm]),
    id!(Xor, 0x00, reg8, reg8, memory_and_register, &[Code::byte(0x30), Code::mrm]),
    id!(Xor, 0x00, mem, reg16, memory_and_register, &[Code::byte(0x31), Code::mrm]),
    id!(Xor, 0x00, reg16, reg16, memory_and_register, &[Code::byte(0x31), Code::mrm]),
    id!(Xor, 0x00, reg8, mem, register_and_memory, &[Code::byte(0x32), Code::mrm]),
    id!(Xor, 0x00, reg8, reg8, register_and_memory, &[Code::byte(0x32), Code::mrm]),
    id!(Xor, 0x00, reg16, mem, register_and_memory, &[Code::byte(0x33), Code::mrm]),
    id!(Xor, 0x00, reg16, reg16, register_and_memory, &[Code::byte(0x33), Code::mrm]),
    id!(Xor, 0x00, rm16, imm8, memory_immediate, &[Code::byte(0x83), Code::encoding(0x06), Code::ibs]),
    id!(Xor, 0x00, al, imm, immediate_source, &[Code::byte(0x34), Code::ib]),
    id!(Xor, 0x00, ax, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x06), Code::ibs]),
    id!(Xor, 0x00, ax, imm, immediate_source, &[Code::byte(0x35), Code::iw]),
    id!(Xor, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x80), Code::encoding(0x06), Code::ib]),
    id!(Xor, 0x00, rm16, sbyteword, memory_immediate, &[Code::byte(0x83), Code::encoding(0x06), Code::ibs]),
    id!(Xor, 0x00, rm16, imm, memory_immediate, &[Code::byte(0x81), Code::encoding(0x06), Code::iw]),
    id!(Xor, 0x00, mem, imm8, memory_immediate, &[Code::byte(0x80), Code::encoding(0x06), Code::ib]),
    id!(Xor, 0x00, mem, sbyteword16, memory_immediate, &[Code::byte(0x83), Code::encoding(0x06), Code::ibs]),
    id!(Xor, 0x00, mem, imm16, memory_immediate, &[Code::byte(0x81), Code::encoding(0x06), Code::iw]),
    id!(Xor, 0x00, rm8, imm, memory_immediate, &[Code::byte(0x82), Code::encoding(0x06), Code::ib]),
];

#[derive(Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum Operation {
    Aaa,
    Aad,
    Aam,
    Aas,
    Adc,
    Add,
    And,
    Call,
    Cbw,
    Clc,
    Cld,
    Cli,
    Cmc,
    Cmp,
    Cmpsb,
    Cmpsw,
    Cwd,
    Daa,
    Das,
    Dec,
    Div,
    Fwait,
    Hlt,
    Idiv,
    Imul,
    In,
    Inc,
    Int,
    Int03,
    Int3,
    Into,
    Iret,
    Jcxz,
    Jmp,
    Lahf,
    Lds,
    Lea,
    Les,
    Lodsb,
    Lodsw,
    Loop,
    Loope,
    Loopne,
    Loopnz,
    Loopz,
    Mov,
    Movsb,
    Movsw,
    Mul,
    Neg,
    Nop,
    Not,
    Or,
    Out,
    Pop,
    Popf,
    Popfw,
    Push,
    Pushf,
    Pushfw,
    Rcl,
    Rcr,
    Ret,
    Retf,
    Rol,
    Ror,
    Sahf,
    Sal,
    Salc,
    Sar,
    Sbb,
    Scasb,
    Scasw,
    Shl,
    Shr,
    Stc,
    Std,
    Sti,
    Stosb,
    Stosw,
    Sub,
    Test,
    Xchg,
    Xlat,
    Xlatb,
    Xor,
}

pub fn str_to_operation(s: &str) -> Option<Operation> {
    Some(match s.to_lowercase().as_str() {
        "aaa" => Operation::Aaa,
        "aad" => Operation::Aad,
        "aam" => Operation::Aam,
        "aas" => Operation::Aas,
        "adc" => Operation::Adc,
        "add" => Operation::Add,
        "and" => Operation::And,
        "call" => Operation::Call,
        "cbw" => Operation::Cbw,
        "clc" => Operation::Clc,
        "cld" => Operation::Cld,
        "cli" => Operation::Cli,
        "cmc" => Operation::Cmc,
        "cmp" => Operation::Cmp,
        "cmpsb" => Operation::Cmpsb,
        "cmpsw" => Operation::Cmpsw,
        "cwd" => Operation::Cwd,
        "daa" => Operation::Daa,
        "das" => Operation::Das,
        "dec" => Operation::Dec,
        "div" => Operation::Div,
        "fwait" => Operation::Fwait,
        "hlt" => Operation::Hlt,
        "idiv" => Operation::Idiv,
        "imul" => Operation::Imul,
        "in" => Operation::In,
        "inc" => Operation::Inc,
        "int" => Operation::Int,
        "int03" => Operation::Int03,
        "int3" => Operation::Int3,
        "into" => Operation::Into,
        "iret" => Operation::Iret,
        "jcxz" => Operation::Jcxz,
        "jmp" => Operation::Jmp,
        "lahf" => Operation::Lahf,
        "lds" => Operation::Lds,
        "lea" => Operation::Lea,
        "les" => Operation::Les,
        "lodsb" => Operation::Lodsb,
        "lodsw" => Operation::Lodsw,
        "loop" => Operation::Loop,
        "loope" => Operation::Loope,
        "loopne" => Operation::Loopne,
        "loopnz" => Operation::Loopnz,
        "loopz" => Operation::Loopz,
        "mov" => Operation::Mov,
        "movsb" => Operation::Movsb,
        "movsw" => Operation::Movsw,
        "mul" => Operation::Mul,
        "neg" => Operation::Neg,
        "nop" => Operation::Nop,
        "not" => Operation::Not,
        "or" => Operation::Or,
        "out" => Operation::Out,
        "pop" => Operation::Pop,
        "popf" => Operation::Popf,
        "popfw" => Operation::Popfw,
        "push" => Operation::Push,
        "pushf" => Operation::Pushf,
        "pushfw" => Operation::Pushfw,
        "rcl" => Operation::Rcl,
        "rcr" => Operation::Rcr,
        "ret" => Operation::Ret,
        "retf" => Operation::Retf,
        "rol" => Operation::Rol,
        "ror" => Operation::Ror,
        "sahf" => Operation::Sahf,
        "sal" => Operation::Sal,
        "salc" => Operation::Salc,
        "sar" => Operation::Sar,
        "sbb" => Operation::Sbb,
        "scasb" => Operation::Scasb,
        "scasw" => Operation::Scasw,
        "shl" => Operation::Shl,
        "shr" => Operation::Shr,
        "stc" => Operation::Stc,
        "std" => Operation::Std,
        "sti" => Operation::Sti,
        "stosb" => Operation::Stosb,
        "stosw" => Operation::Stosw,
        "sub" => Operation::Sub,
        "test" => Operation::Test,
        "xchg" => Operation::Xchg,
        "xlat" => Operation::Xlat,
        "xlatb" => Operation::Xlatb,
        "xor" => Operation::Xor,
        _ => return None,
    })
}
